dateModified: 1566064218
email:
  fromEmail: andrew@nystudio107.com
  fromName: $SITE_NAME
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  d08a0d16-0e00-49e6-9cd4-465fa2d65d7d:
    name: Errors
  efc44cb8-5a29-4f4b-8977-cf6ee112e601:
    name: Common
fields:
  a5cb77be-c4d9-4d3e-88fb-d5384ca13941:
    name: 'Error Image'
    handle: errorImage
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: ''
      defaultUploadLocationSource: 'volume:5c642d7e-b16b-4836-9575-668d75d242e5'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:5c642d7e-b16b-4836-9575-668d75d242e5'
      singleUploadLocationSubpath: ''
      restrictFiles: '1'
      allowedKinds:
        - image
      sources:
        - 'volume:5c642d7e-b16b-4836-9575-668d75d242e5'
      source: null
      targetSiteId: null
      viewMode: large
      limit: '1'
      selectionLabel: ''
      localizeRelations: false
      validateRelatedElements: ''
    contentColumnType: string
    fieldGroup: d08a0d16-0e00-49e6-9cd4-465fa2d65d7d
  b8ba7115-3804-4c06-8a96-501963d1fc5c:
    name: 'Error Headline'
    handle: errorHeadline
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: d08a0d16-0e00-49e6-9cd4-465fa2d65d7d
  e6d658aa-c335-4f15-bbcd-59fe05d9e913:
    name: 'Error Text'
    handle: errorText
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: '1'
      initialRows: '4'
      charLimit: ''
      columnType: text
    contentColumnType: text
    fieldGroup: d08a0d16-0e00-49e6-9cd4-465fa2d65d7d
plugins:
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  fastcgi-cache-bust:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-optimize:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retour:
    edition: standard
    enabled: true
    schemaVersion: 3.0.7
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.8
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  webperf:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
sections:
  54e60257-f31a-44aa-960e-bbd364197e28:
    name: Homepage
    handle: homepage
    type: single
    enableVersioning: false
    propagationMethod: all
    siteSettings:
      66514b58-f1c7-480d-b3d5-aca0b7d78f45:
        enabledByDefault: true
        hasUrls: true
        uriFormat: __home__
        template: index
    entryTypes:
      fb3a8f31-d1cc-4c13-903b-a501f7e51f54:
        name: Homepage
        handle: homepage
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
  a72bfe0c-3389-4f9f-8ec1-ab318ec10b29:
    name: Errors
    handle: errors
    type: channel
    enableVersioning: false
    propagationMethod: all
    siteSettings:
      66514b58-f1c7-480d-b3d5-aca0b7d78f45:
        enabledByDefault: true
        hasUrls: false
        uriFormat: null
        template: null
    entryTypes:
      faceb3ed-6771-453c-9c2a-aa330847f6db:
        name: Errors
        handle: errors
        hasTitleField: true
        titleLabel: Title
        titleFormat: null
        sortOrder: 1
siteGroups:
  29a5becc-aa82-4ea8-a790-5056591e422d:
    name: $SITE_NAME
sites:
  66514b58-f1c7-480d-b3d5-aca0b7d78f45:
    name: $SITE_NAME
    handle: default
    language: en-US
    hasUrls: true
    baseUrl: $SITE_URL
    sortOrder: 1
    primary: true
    siteGroup: 29a5becc-aa82-4ea8-a790-5056591e422d
system:
  edition: solo
  name: $SITE_NAME
  live: true
  schemaVersion: 3.2.16
  timeZone: America/New_York
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  5c642d7e-b16b-4836-9575-668d75d242e5:
    name: Site
    handle: site
    type: craft\volumes\Local
    hasUrls: true
    url: '@assetsUrl/assets/site'
    settings:
      path: '@webroot/assets/site'
    sortOrder: 1
